# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewer',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('follows', models.PositiveIntegerField()),
                ('followers', models.PositiveIntegerField()),
            ],
        ),
    ]
