# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertiser',
            fields=[
                ('advertiserId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('showTime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('channelId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_multiplier', models.PositiveIntegerField()),
                ('creationDate', models.DateField(auto_now=True)),
                ('advertiserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.advertiser')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genreId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('subscriptionId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('channelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.channel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('videoId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('views', models.PositiveIntegerField()),
                ('channelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.channel')),
                ('genreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.genre')),
            ],
        ),
        migrations.AddField(
            model_name='advertiser',
            name='genreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.genre'),
        ),
    ]
